---
- name: Check MariaDB service
  hosts: all
  gather_facts: false

  tasks:
    - name: Check mariadb active state
      ansible.builtin.raw: systemctl is-active mariadb
      register: mariadb_state
      changed_when: false

    - name: Show mariadb state
      ansible.builtin.debug:
        var: mariadb_state.stdout
